// packages/views/src/components/file-folder/title.vue
<template>
    <span
        :data-key="nodeData.key"
        :data-context="nodeData.type"
        :style="{display: !inputShow ? 'unset' : 'none'}"
        class="ant-tree-title-text"
    >
        {{ title }}
    </span>
    <input
        ref="inputRef"
        :style="{display: inputShow ? 'unset' : 'none'}"
        class="ant-tree-title-search-input"
        @blur="onBlur"
        @keypress="onKeyPress"
    />
</template>

<script setup lang="ts">
import {ref, watch, nextTick} from 'vue';
import './title.less';

interface NodeData {
    title?: string;
    type?: string;
    key: string | number;
    path?: string;
    name?: string;
    exist?: boolean;
}

const props = withDefaults(defineProps<{
    nodeData: NodeData;
    rename?: boolean;
    onRename?: (oldPath: string, newName: string, nodeData: Record<string, any>) => Promise<any>;
}>(), {
    rename: false
});

const inputShow = ref(false);
const title = ref(props.nodeData.title || '');
const inputRef = ref<HTMLInputElement | null>(null);

watch(() => props.rename, (val) => {
    if (val) {
        inputShow.value = true;
        nextTick(() => {
            if (inputRef.value) {
                inputRef.value.value = typeof props.nodeData.title === 'string' ? props.nodeData.title : '';
                inputRef.value.focus();
            }
        });
    } else {
        inputShow.value = false;
    }
});

watch(() => props.nodeData.exist, (val) => {
    if (!val) {
        inputShow.value = true;
        setTimeout(() => {
            if (inputRef.value) {
                inputRef.value.value = typeof props.nodeData.title === 'string' ? props.nodeData.title : '';
                inputRef.value.focus();
            }
        }, 60);
    }
});

function handleRename() {
    const newName = inputRef.value?.value.trim();
    if (!newName) return;
    if (props.nodeData.path && typeof props.onRename === 'function') {
        props.onRename(props.nodeData.path, newName, props.nodeData)
            .then((res: string) => {
                title.value = res ? newName : (props.nodeData.title || '');
                inputShow.value = false;
            })
            .catch(err => console.log(err));
    }
}

function onKeyPress(e: KeyboardEvent) {
    if (e.key === 'Enter') {
        handleRename();
    }
}

function onBlur() {
    handleRename();
}
</script>

// packages/views/src/components/file-folder/title.tsx
import * as React from 'react';
import './title.less';

function noop() {}

interface ITitileProps {
    nodeData: {
        title?: React.ReactNode;
        type?: string;
        key: string | number;
        path?: string;
        name?: string;
        exist?: boolean;
    };
    rename: boolean;
    onRename?: (oldPath: string, newPath: string, nodeData: Record<string, any>) => Promise<any>;
    onBlur?: (data: string) => Promise<any>;
    onKeyPress?: (data: string) => Promise<any>;
}

function Title(props: ITitileProps) {
    const [inputShow, setInputShow] = React.useState<boolean>(false);
    const [title, setTitle] = React.useState<React.ReactNode>(props.nodeData.title);
    const inputRef = React.useRef<HTMLInputElement | null>(null);
    const isMouted = React.useRef<boolean>(false);

    React.useEffect(() => {
        isMouted.current = true;
        if (props.rename) {
            setInputShow(true);
            setTimeout(() => {
                if (inputRef.current) {
                    inputRef.current.value = typeof props.nodeData.title === 'string' ? props.nodeData.title : '';
                    inputRef.current.focus();
                }
            }, 0);
        } else {
            setInputShow(false);
        }
        return () => {
            isMouted.current = false;
        };
    }, [props.rename]);

    React.useEffect(() => {
        if (!props.nodeData.exist) {
            setInputShow(true);
            setTimeout(() => {
                if (inputRef.current) {
                    inputRef.current.value = typeof props.nodeData.title === 'string' ? props.nodeData.title : '';
                    inputRef.current.focus();
                }
            }, 60);
        }
    }, [props.nodeData.exist]);

    const onKeyPress = React.useCallback((e: React.KeyboardEvent) => {
        if (e.key === 'Enter') {
            // 去修改文件名
            // 成功之后需要将文字设置一下，失败了则不设置
            // setInputShow(false);
            const newName = inputRef.current && inputRef.current.value.trim();
            if (!newName) {
                return;
            }
            if (props.nodeData.path) {
                typeof props.onRename === 'function' && props.onRename(
                    props.nodeData.path,
                    newName,
                    props.nodeData
                ).then((res: string) => {
                    if (!res) {
                        setTitle(props.nodeData.title);
                    } else {
                        setTitle(newName);
                    }
                    setInputShow(false);
                }).catch(err => {
                    console.log(err);
                });
            }
        }
    }, [setInputShow, setTitle, inputRef.current]);

    const onBlur = React.useCallback(() => {
        const newName = inputRef.current && inputRef.current.value.trim();
        if (!newName) {
            return;
        }
        if (props.nodeData.path) {
            typeof props.onRename === 'function' && props.onRename(
                props.nodeData.path,
                newName,
                props.nodeData
            ).then((res: string) => {
                if (!res) {
                    setTitle(props.nodeData.title);
                } else {
                    setTitle(newName);
                }
                setInputShow(false);
            }).catch(err => {
                console.log(err);
            });
        }
    }, [setInputShow, setTitle, inputRef.current]);

    return (
        <>
            <span
                data-key={props.nodeData.key}
                data-context={props.nodeData.type}
                style={{display: !inputShow ? 'unset' : 'none'}}
                className="ant-tree-title-text"
            >
                {title}
            </span>
            <input
                ref={inputRef}
                onBlur={onBlur}
                style={{display: inputShow ? 'unset' : 'none'}}
                className="ant-tree-title-search-input"
                onKeyPress={onKeyPress}
            />
        </>
    );
}

Title.defaultProps = {
    onRename: noop,
    onBlur: noop,
    onKeyPress: noop
};

export default React.memo(Title);
