// packages/views/src/pages/editor/editor.tsx
import './editor.less';

import React, {useRef, useEffect, useCallback, useState, useContext} from 'react';
import {useMount} from 'ahooks';
import useCodemirror, {CodemirrorObj} from '../../hooks/useCodemirror';
import {FileContext} from './store/sidbar';
import {EditorContext} from 'views/src/pages/editor/store/editor';

import SplitPane, {Pane} from 'react-split-pane';
import Sider from './components/sider';
import MdView from '../../components/md-view';
import ToolBar from './components/tool-bar';
import Footer from './components/footer';

import {success, error} from 'views/src/utils/message';
import {isFilePath} from 'views/src/utils/tools';

import {fileEvent, FS_SAVE} from 'views/src/utils/event';
import {pandora} from 'views/src/services/pandora';

import {blobToBase64, getFileName} from 'shared/utils/img';
import {uploader} from 'shared/utils/chunk';
import {PROTOCOL_IMG} from 'shared/common/constant';

function Editor() {
    const [storeState] = useContext(FileContext);
    const {
        code,
        setCode,
        setCodemirrorEle,
        scroll: coScroll,
        editor,
        count
    } = useCodemirror();

    /* -------------------------------------------------------------------------- */
    /*                                 handle pic                                 */
    /* -------------------------------------------------------------------------- */
    const [, dispatch] = useContext(EditorContext);
    useEffect(() => {
        dispatch({
            type: 'storeeditor',
            payload: editor
        });
        if (editor) {
            // @ts-ignore
            editor.on('paste', (instance: CodemirrorObj['editor'], e: ClipboardEvent) => {
                if (e.clipboardData && e.clipboardData.items) {
                    const items = e.clipboardData.items;
                    for (let i = 0, len = items.length; i < len; i++) {
                        let item = items[i];
                        if (item.kind !== 'file') {
                            return;
                        }
                        let pasteFile = item.getAsFile();
                        if (!pasteFile) {
                            return;
                        }
                        if (pasteFile.size > 0 && pasteFile.type.match('^image/')) {
                            blobToBase64(pasteFile).then(data => {
                                const imageName = getFileName();
                                // 拒绝压缩
                                uploader({
                                    send(data: any) {
                                        pandora.ipcRenderer.invoke('pandora:storeImage', {
                                            name: imageName,
                                            base64: data
                                        }).then((res: {success: boolean, data: string}) => {
                                            const doc = editor.getDoc();
                                            const curs = doc.getCursor();
                                            doc.replaceRange(
                                                `<img src="${PROTOCOL_IMG}:\/\/${res.data}" width="100%" height="100%" />`,
                                                {line: curs.line, ch: curs.ch}
                                            );
                                        }).catch(err => {
                                            console.warn(err);
                                        });
                                    }
                                }, data as string);
                            }).catch(error => {
                                console.log(error);
                            });
                        }
                        return;
                    }
                }
            });
        }
    }, [editor]);

    /* -------------------------------------------------------------------------- */
    /*                                    侧边栏展开                               */
    /* -------------------------------------------------------------------------- */
    const sideRef = useRef<HTMLDivElement | null>(null);
    useEffect(() => {
        if (sideRef && sideRef.current) {
            sideRef.current.style.width = storeState.sidbarOpened ? '30%' : '0px';
        }
    }, [storeState.sidbarOpened, sideRef.current]);

    /* -------------------------------------------------------------------------- */
    /*                                    文件操作                                 */
    /* -------------------------------------------------------------------------- */
    const scrollTarget = useRef<number>(-1);
    const [mdScroll, setMdScroll] = useState<any>({
        scrollTop: 0,
        scrollHeight: 0
    });
    // 获取文件code.TODO: 确保组件没有卸载
    useEffect(() => {
        if (isFilePath(storeState.selectedFilePath) && pandora) {
            pandora.ipcRenderer.invoke('pandora:readFile', storeState.selectedFilePath).then((resStr: string) => {
                setCode(resStr);
                editor?.getDoc().setValue(resStr);
            }).catch(err => {
                console.warn(err);
            });
        } else {
            setCode('');
            editor?.getDoc().setValue('');
        }
    }, [storeState.selectedFilePath, setCode, editor]);

    // 保存文件内容
    const saveFileCb = useCallback(async () => {
        const content = editor?.getDoc().getValue() || '';
        if (!storeState.selectedFilePath) {
            // TODO：保存文件弹窗
            error('保存文件失败');
            return;
        }
        // TODO:错误处理
        pandora && pandora.ipcRenderer.invoke('pandora:writeFile', storeState.selectedFilePath, content).then(() => {
            success('保存文件成功');
        }).catch(err => {
            console.log(err);
        });
    }, [storeState.selectedFilePath]);

    // 监听保存文件内容的事件 TODO: saveFileCb 会一直变化
    useEffect(() => {
        fileEvent.removeAllListeners(FS_SAVE);
        fileEvent.on(FS_SAVE, saveFileCb);
    }, [saveFileCb]);

    /* -------------------------------------------------------------------------- */
    /*                                    滚动相关                                 */
    /* -------------------------------------------------------------------------- */
    const mdRef = useRef<HTMLDivElement | null>(null);
    const editorRef: React.RefObject<HTMLDivElement> = useRef(null);
    useMount(() => {
        setCodemirrorEle(editorRef.current as Element);
        const ele = mdRef.current;
        if (ele) {
            ele.addEventListener('scroll', mdScrollHandler);
            ele.addEventListener('mouseover', mdMouseHandler);
        }
        return () => {
            mdRef.current?.removeEventListener('scroll', mdScrollHandler);
            mdRef.current?.removeEventListener('mouseover', mdMouseHandler);
        };
    });

    const mdScrollHandler = useCallback(
        (evt: any) => {
            let {scrollTop, scrollHeight} = evt.target;
            setMdScroll({scrollTop, scrollHeight});
        },
        [],
    );
    const mdMouseHandler = useCallback(
        () => {
            scrollTarget.current = 1;
        },
        [scrollTarget],
    );
    const getCoViewEle = useCallback(
        (ele: HTMLDivElement) => {
            ele && ele.addEventListener('mouseover', () => {
                scrollTarget.current = 0;
            });
        },
        []
    );

    useEffect(() => {
        const layerDom = mdRef.current;
        let mdScrollHeight = layerDom!.scrollHeight - layerDom!.clientHeight;
        let coScrollHeight = coScroll.scrollHeight - coScroll.clientHeight;
        if (scrollTarget.current === 1) {
            let coScrollTop = mdScroll.scrollTop / mdScrollHeight * coScrollHeight;
            editor && editor.scrollTo(null, coScrollTop);
        }
        else {
            let mdScrollTop = coScroll.scrollTop / coScrollHeight * mdScrollHeight;
            mdRef.current && mdRef.current.scrollTo(0, mdScrollTop);
        }
    }, [
        coScroll.scrollTop,
        coScroll.scrollHeight,
        coScroll.clientHeight,
        mdScroll.scrollTop,
        mdScroll.scrollHeight,
        editor
    ]);

    return (
        <div className="pandora-editor">
            {
                pandora && <Sider
                    className="editor-file-folder"
                    ref={sideRef}
                />
            }
            <div className="editor-container">
                <ToolBar />
                <div className="editor-wrapper">
                    <SplitPane
                        split="vertical"
                        defaultSize="50%"
                        paneStyle={{overflow: 'auto'}}
                        style={{position: 'relative'}}
                    >
                        <Pane
                            eleRef={getCoViewEle}
                            className="md-editor-wrapper"
                            style={{height: '100%'}}
                        >
                            <div
                                ref={editorRef}
                                className="md-editor-container"
                            ></div>
                        </Pane>
                        <Pane className="md-view-wrapper">
                            <div ref={mdRef} className="md-view-layer">
                                <MdView
                                    value={code}
                                    className="md-view-container"
                                />
                            </div>
                            <div className="iphone-frame"></div>
                        </Pane>
                    </SplitPane>
                </div>
                <Footer count={count} />
            </div>
        </div>
    );
}

export default Editor;

// packages/views/src/pages/editor/editor.vue
<template>
    <div class="pandora-editor">
        <Sider v-if="pandora" class-name="editor-file-folder" ref="siderComp" />
        <div class="editor-container">
            <ToolBar />
            <div class="editor-wrapper">
                <div class="editor-split-pane" style="position: relative">
                    <div
                        class="md-editor-wrapper"
                        style="height: 100%; overflow: auto; flex: 1"
                        @mouseover="scrollTarget = 0"
                    >
                        <div ref="editorRef" class="md-editor-container"></div>
                    </div>
                    <div class="md-view-wrapper" style="flex: 1">
                        <div ref="mdRef" class="md-view-layer" @mouseover="scrollTarget = 1">
                            <MdView :value="code" class-name="md-view-container" />
                        </div>
                        <div class="iphone-frame"></div>
                    </div>
                </div>
            </div>
            <EditorFooter :count="count" />
        </div>
    </div>
</template>

<script setup lang="ts">
import {ref, watch, onMounted, onUnmounted} from 'vue';
import './editor.less';
import useCodemirror from 'views/src/hooks/useCodemirror';
import {useSidebarStore} from './store/sidebar';
import {useEditorStore} from './store/editor';

import Sider from './components/sider/index.vue';
import MdView from 'views/src/components/md-view/index.vue';
import ToolBar from './components/tool-bar/index.vue';
import EditorFooter from './components/footer/index.vue';

import {success, error} from 'views/src/utils/message';
import {isFilePath} from 'views/src/utils/tools';
import {fileEvent, FS_SAVE} from 'views/src/utils/event';
import {pandora} from 'views/src/services/pandora';

import {blobToBase64, getFileName} from 'shared/utils/img';
import {uploader} from 'shared/utils/chunk';
import {PROTOCOL_IMG} from 'shared/common/constant';

const sidebarStore = useSidebarStore();
const editorStore = useEditorStore();

const {code, setCode, editorRef, scroll: coScroll, editor, count} = useCodemirror();

const siderComp = ref<any>(null);
const mdRef = ref<HTMLDivElement | null>(null);
const scrollTarget = ref(0);
const mdScroll = ref({scrollTop: 0, scrollHeight: 0});

// Store editor instance in pinia
watch(editor, (cm) => {
    editorStore.storeEditor(cm as any);
    if (cm) {
        // @ts-ignore
        cm.on('paste', (_instance: any, e: ClipboardEvent) => {
            if (e.clipboardData?.items) {
                const items = e.clipboardData.items;
                for (let i = 0; i < items.length; i++) {
                    const item = items[i];
                    if (item.kind !== 'file') return;
                    const pasteFile = item.getAsFile();
                    if (!pasteFile) return;
                    if (pasteFile.size > 0 && pasteFile.type.match('^image/')) {
                        blobToBase64(pasteFile).then(data => {
                            const imageName = getFileName();
                            uploader({
                                send(data: any) {
                                    pandora.ipcRenderer.invoke('pandora:storeImage', {
                                        name: imageName,
                                        base64: data
                                    }).then((res: {success: boolean; data: string}) => {
                                        const doc = cm.getDoc();
                                        const curs = doc.getCursor();
                                        doc.replaceRange(
                                            `<img src="${PROTOCOL_IMG}:\/\/${res.data}" width="100%" height="100%" />`,
                                            {line: curs.line, ch: curs.ch}
                                        );
                                    }).catch((err: any) => console.warn(err));
                                }
                            }, data as string);
                        }).catch((e: any) => console.log(e));
                    }
                    return;
                }
            }
        });
    }
});

// Sidebar width
watch(() => sidebarStore.sidebarOpened, (opened) => {
    const el = siderComp.value?.siderRef;
    if (el) {
        el.style.width = opened ? '30%' : '0px';
    }
});

// Read file when selected file changes
watch(() => sidebarStore.selectedFilePath, (filePath) => {
    if (isFilePath(filePath) && pandora) {
        pandora.ipcRenderer.invoke('pandora:readFile', filePath).then((resStr: string) => {
            setCode(resStr);
            editor.value?.getDoc().setValue(resStr);
        }).catch((err: any) => console.warn(err));
    } else {
        setCode('');
        editor.value?.getDoc().setValue('');
    }
});

// Save file
function saveFileCb() {
    const content = editor.value?.getDoc().getValue() || '';
    if (!sidebarStore.selectedFilePath) {
        error('保存文件失败');
        return;
    }
    pandora?.ipcRenderer.invoke('pandora:writeFile', sidebarStore.selectedFilePath, content).then(() => {
        success('保存文件成功');
    }).catch((err: any) => console.log(err));
}

watch(() => sidebarStore.selectedFilePath, () => {
    fileEvent.removeAllListeners(FS_SAVE);
    fileEvent.on(FS_SAVE, saveFileCb);
}, {immediate: true});

// Scroll sync
function mdScrollHandler(evt: Event) {
    const target = evt.target as HTMLElement;
    mdScroll.value = {
        scrollTop: target.scrollTop,
        scrollHeight: target.scrollHeight
    };
}

onMounted(() => {
    const ele = mdRef.value;
    if (ele) {
        ele.addEventListener('scroll', mdScrollHandler);
    }
});

onUnmounted(() => {
    mdRef.value?.removeEventListener('scroll', mdScrollHandler);
});

// Bidirectional scroll sync
watch([coScroll, mdScroll], () => {
    const layerDom = mdRef.value;
    if (!layerDom || !editor.value) return;
    const mdScrollHeight = layerDom.scrollHeight - layerDom.clientHeight;
    const coScrollHeight = coScroll.value.scrollHeight - coScroll.value.clientHeight;
    if (mdScrollHeight <= 0 || coScrollHeight <= 0) return;

    if (scrollTarget.value === 1) {
        const coScrollTop = mdScroll.value.scrollTop / mdScrollHeight * coScrollHeight;
        editor.value.scrollTo(null, coScrollTop);
    } else {
        const mdScrollTop = coScroll.value.scrollTop / coScrollHeight * mdScrollHeight;
        layerDom.scrollTo(0, mdScrollTop);
    }
});
</script>
