// packages/views/src/components/md-view/index.tsx
/**
 * @file
 */
import React, {useEffect, useState} from 'react';
import {getMd} from 'core/md';
import './index.less';

interface MdViewProps {
    className?: string;
    value: string;
}

let md = getMd('wx', {html: true});

export default function MdView(props: MdViewProps) {
    const [mdString, setMdString] = useState<string>('');
    useEffect(() => {
        setMdString(md.render(props.value));
    }, [props.value]);
    return (
        <div
            className={props.className}
            dangerouslySetInnerHTML={{__html: mdString}}
        ></div>
    );
}

MdView.defaultProps = {
    className: '',
    value: ''
};

// packages/views/src/components/md-view/index.vue
<template>
    <div :class="className" v-html="mdString"></div>
</template>

<script setup lang="ts">
import {ref, watch} from 'vue';
import {getMd} from 'core/md';
import './index.less';

const props = withDefaults(defineProps<{
    className?: string;
    value?: string;
}>(), {
    className: '',
    value: ''
});

const md = getMd('wx', {html: true});
const mdString = ref('');

watch(() => props.value, (val) => {
    mdString.value = md.render(val);
}, {immediate: true});
</script>
